const { Router } = require('express')
const auth = require('../middlewares/auth')
const admin = require('../middlewares/Admin')
const { requirePermission } = require('../middlewares/Admin')
const { PERMISSIONS } = require('../constants/permissions')
const { getDashboardSummaryController, getAllOrdersController, getOrderReportController, getAllUsersController, convertToAdminController, convertToUserController, suspendUserController, activateUserController, getAllProductsLengthController, manageUpcomingOrdersController, refundOrderController } = require('../controllers/adminController')
const { listAccessController, updateAccessController } = require('../controllers/accessController')
const { listOffersController, createOfferController, updateOfferController, setOfferStatusController, deleteOfferController } = require('../controllers/offerController')
const { listNotificationsController, createNotificationController, markNotificationReadController, markAllNotificationsReadController, deleteNotificationController } = require('../controllers/notificationController')

const adminRouter = Router()
const { listTablesController, createTableController, updateTableController, deleteTableController } = require('../controllers/tableController')
const { listBannersController, createBannerController, updateBannerController, deleteBannerController, reorderBannersController, setBannerStatusController } = require('../controllers/bannerController')
const { listInventoryController, adjustInventoryController } = require('../controllers/inventoryController')


adminRouter.use(auth, admin)
adminRouter.get('/dashboard-summary', requirePermission(PERMISSIONS.DASHBOARD_VIEW), getDashboardSummaryController)
adminRouter.get('/upcoming-orders', requirePermission(PERMISSIONS.ORDERS_VIEW), getAllOrdersController)
adminRouter.get('/order-reports', requirePermission(PERMISSIONS.ORDERS_VIEW), getOrderReportController)
adminRouter.get('/get-all-users', requirePermission(PERMISSIONS.CUSTOMERS_VIEW), getAllUsersController)
adminRouter.post('/make-admin', requirePermission(PERMISSIONS.ACCESS_MANAGE), convertToAdminController)
adminRouter.post('/make-user', requirePermission(PERMISSIONS.ACCESS_MANAGE), convertToUserController)
adminRouter.post('/suspend-user', requirePermission(PERMISSIONS.CUSTOMERS_MANAGE), suspendUserController)
adminRouter.post('/activate-user', requirePermission(PERMISSIONS.CUSTOMERS_MANAGE), activateUserController)
adminRouter.post('/total-product', requirePermission(PERMISSIONS.PRODUCTS_VIEW), getAllProductsLengthController)
adminRouter.post('/manage-order', requirePermission(PERMISSIONS.ORDERS_MANAGE), manageUpcomingOrdersController)
adminRouter.post('/orders/:orderId/refund', requirePermission(PERMISSIONS.ORDERS_MANAGE), refundOrderController)
adminRouter.get('/tables', requirePermission(PERMISSIONS.TABLES_MANAGE), listTablesController)
adminRouter.post('/tables', requirePermission(PERMISSIONS.TABLES_MANAGE), createTableController)
adminRouter.patch('/tables/:publicId', requirePermission(PERMISSIONS.TABLES_MANAGE), updateTableController)
adminRouter.delete('/tables/:publicId', requirePermission(PERMISSIONS.TABLES_MANAGE), deleteTableController)
adminRouter.get('/banners', requirePermission(PERMISSIONS.BANNERS_MANAGE), listBannersController)
adminRouter.post('/banners', requirePermission(PERMISSIONS.BANNERS_MANAGE), createBannerController)
adminRouter.patch('/banners/reorder', requirePermission(PERMISSIONS.BANNERS_MANAGE), reorderBannersController)
adminRouter.patch('/banners/:id/status', requirePermission(PERMISSIONS.BANNERS_MANAGE), setBannerStatusController)
adminRouter.patch('/banners/:id', requirePermission(PERMISSIONS.BANNERS_MANAGE), updateBannerController)
adminRouter.delete('/banners/:id', requirePermission(PERMISSIONS.BANNERS_MANAGE), deleteBannerController)
adminRouter.get('/inventory', requirePermission(PERMISSIONS.INVENTORY_VIEW), listInventoryController)
adminRouter.post('/inventory/:productId/adjust', requirePermission(PERMISSIONS.INVENTORY_MANAGE), adjustInventoryController)
adminRouter.get('/access', requirePermission(PERMISSIONS.ACCESS_MANAGE), listAccessController)
adminRouter.patch('/access/users/:userId', requirePermission(PERMISSIONS.ACCESS_MANAGE), updateAccessController)
adminRouter.get('/offers', requirePermission(PERMISSIONS.OFFERS_VIEW), listOffersController)
adminRouter.post('/offers', requirePermission(PERMISSIONS.OFFERS_MANAGE), createOfferController)
adminRouter.patch('/offers/:id/status', requirePermission(PERMISSIONS.OFFERS_MANAGE), setOfferStatusController)
adminRouter.patch('/offers/:id', requirePermission(PERMISSIONS.OFFERS_MANAGE), updateOfferController)
adminRouter.delete('/offers/:id', requirePermission(PERMISSIONS.OFFERS_MANAGE), deleteOfferController)
adminRouter.get('/notifications', requirePermission(PERMISSIONS.NOTIFICATIONS_VIEW), listNotificationsController)
adminRouter.post('/notifications', requirePermission(PERMISSIONS.NOTIFICATIONS_MANAGE), createNotificationController)
adminRouter.patch('/notifications/read-all', requirePermission(PERMISSIONS.NOTIFICATIONS_VIEW), markAllNotificationsReadController)
adminRouter.patch('/notifications/:id/read', requirePermission(PERMISSIONS.NOTIFICATIONS_VIEW), markNotificationReadController)
adminRouter.delete('/notifications/:id', requirePermission(PERMISSIONS.NOTIFICATIONS_MANAGE), deleteNotificationController)


module.exports = adminRouter
